// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-omBcCx77idORD3tPIZM4f5WBOjd7D4',
    appId: '1:737095072678:web:f79851afb21c142a08ed67',
    messagingSenderId: '737095072678',
    projectId: 'anpoda-metal',
    authDomain: 'anpoda-metal.firebaseapp.com',
    storageBucket: 'anpoda-metal.appspot.com',
    measurementId: 'G-3XC43KNNEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqzyAQDDrVygY59GfVyKWDN2R-DQNL1o',
    appId: '1:737095072678:android:0cfa45edaaea567508ed67',
    messagingSenderId: '737095072678',
    projectId: 'anpoda-metal',
    storageBucket: 'anpoda-metal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2_fLEvVCuDbyMQov3R7jNt2koTbaEBE',
    appId: '1:737095072678:ios:902cc04027f8197b08ed67',
    messagingSenderId: '737095072678',
    projectId: 'anpoda-metal',
    storageBucket: 'anpoda-metal.appspot.com',
    androidClientId: '737095072678-hjv2bctaqo0m6i52epofi6oe9ehu1o23.apps.googleusercontent.com',
    iosClientId: '737095072678-4kq4lt074e7j9aulc6dg6hlgjdspubp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.buyMetalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2_fLEvVCuDbyMQov3R7jNt2koTbaEBE',
    appId: '1:737095072678:ios:902cc04027f8197b08ed67',
    messagingSenderId: '737095072678',
    projectId: 'anpoda-metal',
    storageBucket: 'anpoda-metal.appspot.com',
    androidClientId: '737095072678-hjv2bctaqo0m6i52epofi6oe9ehu1o23.apps.googleusercontent.com',
    iosClientId: '737095072678-4kq4lt074e7j9aulc6dg6hlgjdspubp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.buyMetalApp',
  );
}
